Document: red5-openmeetings
Title: Debian red5-openmeetings Manual
Author: <insert document author here>
Abstract: This manual describes what red5-openmeetings is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/red5-openmeetings/red5-openmeetings.sgml.gz

Format: postscript
Files: /usr/share/doc/red5-openmeetings/red5-openmeetings.ps.gz

Format: text
Files: /usr/share/doc/red5-openmeetings/red5-openmeetings.text.gz

Format: HTML
Index: /usr/share/doc/red5-openmeetings/html/index.html
Files: /usr/share/doc/red5-openmeetings/html/*.html


